### ISSUE TITLE
Dual SIM phone problem

### ISSUE THREAD

**Issue by dejvicna** [avast/sms-ticket#23]
Hello.. I've got problem with application od ma dual SIM phone - it's unable to choose, from which SIM I want to send premium SMS. App is sending SMS hardly from SIM 2, which has not alloowed premium SMS. Please give user to choose, which SIM he want to use..
 Thank you..
  David

**Comment by TomasKypta** [comment]
Hi, could you write the type of your phone and version of Android OS? Thanks.

I have to warn that we can't guarantee successful fix because dual SIM phones are very problematic from programmers point of view. Before Lollipop there were no APIs for handling multi SIM phones. Some APIs were added in Lollipop and even with these it's still rather problematic to work with multi SIM phones. Multi SIM phones usually have many manufacturers' hacks to Android OS which are difficult/impossible to access by 3rd party apps.

**Comment by dejvicna** [comment]
Asus Zenfone 5, Android 5.0

**Comment by davidvavra** [comment]
I have finished implementation of multi-sim support, see screenshot.

It will work only on devices which have Android 5.1 or newer. Android didn't have official support for dual-sim in earlier releases.

![6](https://cloud.githubusercontent.com/assets/395884/12719507/a553cf8c-c8f5-11e5-9da3-6e8cb5a4d21a.png)
